Table Employees {
    id int [pk]
    firstName varchar
    lastName varchar
    computerId int [ref: - Computers.id]
    departmentId int [ref: > Departments.id]
    locationId int [ref: - Locations.id]
    employeeCustomerId int [ref: > EmployeeCustomers.id]
}

Table Computers {
    id int [pk]
    model varchar
    year int
    
}

Table Departments {
    id int [pk]
    name varchar
}

Table Locations {
    id int [pk]
    location varchar
}

Table Customers {
    id int [pk]
    name varchar
    employeeCustomerId int [ref: > EmployeeCustomers.id]
}

Table EmployeeCustomers {
    id int [pk]
    customerId int [ref: > Customers.id]
    employeeId int [ref: > Employees.id]
}