Table Employees {
    id int [pk]
    firstName varchar
    lastName varchar
    computerId int [ref: - Computers.id]
    departmentId int [ref: > Departments.id]
    locationId int [ref: - Locations.id]
}

Table Computers {
    id int [pk]
    model varchar
    year int
    
}

Table Departments {
    id int [pk]
    name varchar
}

Table Locations {
    id int [pk]
    location varchar
}